### ISSUE TITLE
Synchronous vs Asynchronous callback?

### ISSUE THREAD

**Issue by adriantadros** [krakenjs/confit#25]
Hi there,

In previous versions of KrakenJS, nconf was used instead of confit. If I needed to refer to a config key anywhere in my project, I could do the following:

```javascript
var nconf = require('nconf');
var myVar = nconf.get('myVar');
```

With confit, we need to now use a callback, e.g.

```javascript
var basedir = path.join(__dirname, '/config');
var config = confit(basedir).create(function (err, config) {
  var myVar = config.get('myVar');
});
```

Is the callback really needed? Ideally I would like to just do the following:

```javascript
var basedir = path.join(__dirname, '/config');
var config = confit(basedir);
var myVar = config.get('myVar');
```

It looks like there is a "_store" object where I can extract the config keys I need, without having to execute the "create" command.

For example, this works:
```javascript
var basedir = path.join(__dirname, '/config');
var config = confit(basedir);
var myVar = config._store.myVar;
```

Ideally, I would like to use the 'get' function directly from the config object. Is this an enhancement that can be considered? Or is there a specific reason that confit requires a callback?

Thanks,
Adrian

**Comment by jasisk** [comment]
Hi Adrian,

`nconf` exposes a singleton which means that (nearly) every time you `require('nconf')`, you'll get the same object. This makes accessing a single config trivially easy which—I'll admit—can be pretty handy. It was our experience, however, that the cost outweighs the benefit with this pattern.

First, relying on global state is best avoided when possible. In this particular case, it removes the ability to control the lifecycle of your configuration. As soon as I instantiate a config, that's my config. I cannot _intentionally_ create another instance easily. This starts to get hairy if you are, e.g., composing different applications into a single app.

For example, let's say I have an express application that uses `nconf`:
``` js
var express = require('express');
var config = require('nconf');
var app = module.exports = express();

config.set({ flag: true });

app.get('/', function (req, res) {
    res.send('my flag is ' + config.get('flag'));
});

// if we were called directly, listen on 8000
if (require.main === module) {
    app.listen(8000);
}
```

Everything would work as expected and hitting `/` would tell us that, "my flag is true."

Now let's build a second app (named `app2.js`) that is exactly the same, except now with a `flag` that is `false`. This, too, would work as expected—returning that the flag is false.

But now lets publish the second app, and mount it onto the first:
``` js
// ... snip ...

app.use('/app2', require('app2'));
app.get('/', function (req, res) {
    res.send('my flag is ' + config.get('flag'));
});

// ... snip ...
```

Now, what happens when you visit `/` or `/app2`? We actually can't know without knowing a bit more about your project.

You see, when I said that _nearly_ every `require('nconf')` statement would return the same object, this is a case where that might not be true. In this case (and with the current version of npm), it depends on how / when you installed app2. It also depends on your listed dependencies in both project's `package.json`. You could end up with shared config or you could end up with two copies—both cases are possible.

There are other concerns here, too. For example, everything in nconf is synchronous. There are many, many resources that explain why asynchronous should be preferred over synchronous in node so I won't rehash them here.

Lastly, we recognized a pattern in using configuration that I think goes against a lot of things we as developers try and focus on. A lot of folks began treating configuration as a dumping ground, throwing a bunch of non-configuration into it, pushing and pulling data arbitrarily, etc. Basically, configuration became a glorified `global`.

Think of it this way: when you write a function, do you define a set of parameters for that function or do you pass in a massive blob of all your application properties and let the function pluck out the parameters it wants? I should hope you generally pick the former. The same should go for configuration.

Now lets talk a bit about kraken, itself.

The pattern you're using (create a new confit object each time you need to grab something from your config) could potentially introduce some problems. Taking the example you provided above, you're not registering the same set of shortstop handlers as [kraken does by default](https://github.com/krakenjs/kraken-js/blob/c0a2c4b5bd031a4b5e4be12f6ac2c4aef7490db6/lib/config.js). This means the ad-hoc config you create will not be the same as the one kraken creates.

The config is available to you in three places which should cover almost every case. First, you can access the config in kraken's [onconfig callback](https://github.com/krakenjs/kraken-js#onconfig-function-optional). This is a great place to do any init-time setup. Second, you can alias config properties within the config itself. For example, let's say I want to access a property of the config when setting up custom middleware:

`config.json`
``` json
{
    "customKey": "abcdefg",
    "middleware": {
        "myCustomMiddleware": {
            "module": {
                "name": "path:./middleware/my-custom",
                "arguments": ["config:customKey"]
            }
        }
    }
}
```

`./middleware/my-custom.js`
``` js
module.exports = function customGenerator(key) {
    // ... `key` is `customKey` from my config ...
    return function myCustomMiddleware(req, res, next) {
        // ... and in because nested closure ...
    };
}
```

Third, you can access the config at resolution time in any of your middleware:
`./controllers/main.js`

``` js
module.exports = function (router) {
    router.get('/', function (req, res) {
        var customKey = req.app.kraken.get('customKey');
        // ... `key` is `customKey` from my config ... 
    });
};
```

Those three cases should take care of pretty much every need. In cases where it doesn't, you can certainly pass config values around from `onconfig` or, if necessary, even the entire config. Point is, if you're used to treating configuration as a glorified `global`, it's just revising the way you think of config to be more like you would most other areas of your application development (keep things tight and focused!).

**Comment by adriantadros** [comment]
Thanks for the detailed response.

I was unaware of the ability to read config values via middleware/routes and that looks like a nice clean solution for retrieving config keys within the express request/response cycle.

The reason I asked this question was because I had some worker processes in my project which are executed outside of the express lifecycle which require access to config, (e.g. I have a worker process which can be run from the command line which needs to read a database connection string via confit).

My particular use case does not require the ability to set config values, but only to read config values from the static JSON files. I am following the pattern you described of passing config keys/objects to the functions that require them and am definitely not using the config as a dumping ground for global variables.

Just FYI, for my worker process, I ended up creating a helper object:
```javascript
// This file is /libs/config.js
var path = require('path');
var confit = require('confit');

var basedir = path.join(__dirname, '../config');
var config = confit(basedir);

module.exports = {
  get: function get(key) {
    var obj;

    if (typeof key === 'string' && key.length) {
      key = key.split(':');
      obj = config._store;

      while (obj && key.length) {
        if (obj.constructor !== Object) {
          return undefined;
        }
        obj = obj[key.shift()];
      }
      return obj;
    }
    return undefined;
  }
};
```

In my worker process, I pass my config keys to the function that requires it, as shown below:
```javascript
// This file is /worker.js and is run from command line
var config = require('./libs/config')
var dbConnectionString = config.get('dbConnectionString');
new WorkerProcess(dbConnectionString);
```

The alternative is to not use the helper class at all and use the confit create callback method:
```javascript
var path = require('path');
var confit = require('confit');
var basedir = path.join(__dirname, '../config');
confit(basedir).create(function(err, config) {
  var dbConnectionString = config.get('dbConnectionString');
  new WorkerProcess(dbConnectionString);
});
```

But I was just trying to avoid wrapping my code inside the confit create callback function.

**Comment by totherik** [comment]
Is this issue still unresolved or can this be closed?

**Comment by pvenkatakrishnan** [comment]
Closing this out due to inactivity.Please reopen if there are open questions still.
