### ISSUE TITLE
Is there a reason Framework#create doesn't return the promise?

### ISSUE THREAD

**Issue by agokjr** [krakenjs/confit#51]
Is there a reason Framework#create doesn't return the promise?

ps. if you need to support cb Bluebird does it nicely.

**Comment by thefotios** [comment]
Second this request. For example

``` javascript
import confit from 'confit';
const config = confit(...).create();

config.then((cfg) => {
  console.log(cfg.get('env:env');
  ...
});
```

**Comment by jasisk** [comment]
```

**Comment by jasisk** [comment]
```
import confit from 'confit';
confit.create((err, config) => {});

**Comment by jasisk** [comment]
Ack. Slack `⌃ + Enter` muscle memory had me submit two essentially blank comments. Sorry for the spam.

There are a bazillion interface discussions on the internet—and Promise v Callback has been one of the most religious since Node introduced (then removed) promise-support in the super early days.

In the case on `confit`, returning a promise or calling a callback will have the same result. There is no ambiguity about the interface—it's always async. In that case, as a module to be consumed programmatically, I'm of the opinion that the simplest interface is best. There is nothing more performant in this case than a simple function call and if a user wants a different interface, it's pretty straightforward to go between them.

That's not to say a promise interface is bad, just that I'd rather leave that up the the module consumer.

For example, here's a promisified confit:

``` js
// ./lib/config.js
import confit from 'confit';
export default function confitPromise(opts) {
  return new Promise((resolve, reject) => {
    confit(opts).create((err, config) => {
      if (err) return reject(err);
      resolve(config);
    });
  });
}

// index.js
import config from './lib/config';
config().then(useConfig).catch(somethingsWrong);
```

... any other @krakenjs/owners want to chime in?

**Comment by pvenkatakrishnan** [comment]
I am leaning towards @jasisk's take on this. At the most basic level, libraries providing a callback like interface is also similar to node core modules' interfaces. Promisifying is just a step away for consumers of a library and with their choice of Promise libraries too :)

**Comment by tlivings** [comment]
I agree with all of the above, although I'd not object to a simple promise wrapping on absence of a callback.

This would, however, be inconsistent (today) with the patterns we've chosen more broadly in the kraken tools. 

More so than `then`, `await confit(options).create()` is sort of nice.

**Comment by tkambler** [comment]
Agree w/ @jasisk. Libraries such as this should stick to generic callback interfaces. If the consumer wants a promise, let them promisify it themselves - which is exactly what we're doing.

**Comment by ethanresnick** [comment]
> More so than then, await confit(options).create() is sort of nice.

I second this...with `await` becoming a first-class construct, having some built-in way to get the Promise out would when a callback isn't provided would be much nicer than having to wrap it myself.

**Comment by grawk** [comment]
I think we're pretty set on not addressing this with a PR from within the team at this time. If anyone does send a PR related to this we can revisit.
